### ISSUE TITLE
Format Price value for PitPoints

### ISSUE THREAD

**Issue by SaranyaBalakrishnan** [airbnb/rheostat#122]
I formatted the price with comma and passed it to pitPoints. [eg: 1,23,400]. But I am unable to pass the values into pitPoints. As it is defined with 'PropTypes.arrayOf(PropTypes.number)'. When I format with comma, It treated as string and produce the below error.
'Failed prop type: Invalid prop `pitPoints[0]` of type `string` supplied to `Rheostat`, expected `number`.'
Please respond to the above question.

Thanks,
Saranya

**Comment by ljharb** [comment]
`1,23,400` isn't a number. In JS, numbers have no separators and decimal values are separated by a `.`.

Passing a number as a formatted string is still not passing a number; don't format it.

**Comment by SaranyaBalakrishnan** [comment]
@ljharb , Thanks for the reply. 

But as per my requirement, I am using rheostat as a price slider. I need the price to be formatted with comma. That formatted price needs to be displayed in the slider. 
Do you have any suggestions on that?

**Comment by ljharb** [comment]
Pass a PitComponent, and map the children value to your desired display label.

**Comment by SaranyaBalakrishnan** [comment]
@ljharb  Thanks .
