### ISSUE TITLE
Support overriding validatePosition

### ISSUE THREAD

**Issue by tomlagier** [airbnb/rheostat#125]
We'd like to implement two independent ranges on a single slider - The left handle would map from [0, leftMax], and the right would map to [rightMin, 100]. 

An easy way to support this without having to seriously extend the slider would be to allow the overriding of the ~~canMove~~ validatePosition function. If there is is appetite, I will submit a PR adding canMove to props and some tests.

**Comment by tomlagier** [comment]
After looking at the behavior I've come to the conclusion that the better method to override is validatePosition because we can use that to return the nearest valid position rather than simply disallowing positions (which works better for clicking and snapping). I'll be resubmitting my PR.

**Comment by ljharb** [comment]
Please update your existing pr instead of closing and reopening :-)

**Comment by tomlagier** [comment]
PR has been updated!

**Comment by ljharb** [comment]
Closed in #126
