### ISSUE TITLE
Missing main extension break eslint-import-resolver-node

### ISSUE THREAD

**Issue by samouss** [airbnb/rheostat#135]
The recent change made to the `package.json` breaks the default configuration of the `eslint-import-resolver-node`. Since by default the node resolver only support `['.js', '.json']` it's not able to find the `rheostat` package because the `jsnext:main` point to a `.jsx` file.

IMO we should revert the change in order to avoid to consumer of the package to explicitly set the support of the `jsx` extension in `eslint-import-resolver-node`.

> https://github.com/airbnb/rheostat/commit/334b6cc589627b4ba2d0a1a6daad8095cb99f994#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L5

**Comment by ljharb** [comment]
jsnext:main is nonstandard and this package should never have set it in the first place. I’d prefer to remove it entirely.

That said, I’ll revert the extension removal for it and rerelease later today.

**Comment by samouss** [comment]
@ljharb thanks a lot!
