### ISSUE TITLE
When updating value prop onChange is triggered

### ISSUE THREAD

**Issue by madou** [airbnb/rheostat#137]
I would imagine onChange would only be called if the value was changed as a result of a keyboard or click interaction.

But it's called when the `value` prop has changed as well.

Intended, or not?

For now I'm using `onValuesUpdated` to let me know if the user is in the process of updating the value, and then resetting it when `onChange` is called.

**Comment by ljharb** [comment]
"on change" suggests to me that it should fire whenever there's been any change at all; the source of that change is irrelevant.

**Comment by madou** [comment]
Well maybe, but that's not how controlled input components work in react.. if they did we'd get into infinite loops wouldn't we? 😬

**Comment by madou** [comment]
Sure I'll make a webpack bin real quick.

**Comment by ljharb** [comment]
"on a button press" is as a result of user interaction, why wouldn't that trigger onChange?

**Comment by madou** [comment]
i'll create an example so we have something to talk about, give me a bit.

**Comment by madou** [comment]
@ljharb hey, made an example repo -> https://github.com/madou/rheostat-double-onchange

wanted to use webpack bin but it isn't working atm.

from the example - i would have thought rheostat wouldn't call onchange if i set the value outside of it. but it's calling it. whats your thoughts?

**Comment by goatslacker** [comment]
Yup, it looks like `onChange` [is called whenever values change](https://github.com/airbnb/rheostat/blob/dd2e23bf7ccb8edf8c9087eb1ada673bc70412ea/src/Slider.jsx#L203). The documentation states that `onChange` is called when the values are "committed" which happens by drag, click, keyboard input, and props change.

We should maybe not do it when props change to your point of not having it trigger an infinite loop but I think that line is there for a reason.

Perhaps what we need is an event that fires only when the slider is changed in a non-programmatic way.

**Comment by madou** [comment]
hey! maybe.

i think the default expectation (well myself at least, haha) using controlled input components is it only gets triggered from the component itself trying to change. so i don't think it would be completely left field to make it do that.

breaking change though.

**Comment by Sunny-Nishan** [comment]
@madou Yes, I was expecting the same, I was expecting it to be called only when the user interacts directly with the slider like it happens for controlled inputs.

**Comment by nshelar** [comment]
Since onChange is called even when the props change, had to do a workaround as mentioned by @madou. I second @goatslacker for adding an event that fires only when slider is changed by the user.

**Comment by jacobbuck** [comment]
I'm seeing the `onChange` getting called when the `min`/`max` props changing, but not the `values`. Perhaps the `onChange` should only call if `values` have changed from being outside `min`/`max` range 🤔
