### ISSUE TITLE
Rheostat handle renders off slide track when min value is greater than zero

### ISSUE THREAD

**Issue by strange-developer** [airbnb/rheostat#142]
I'm currently using Rheostat with the following code:

```
<Rheostat min={5} max={50} />
```

When the slider renders, the slide handle is not shown on the slide track. I've been trying to figure it out but haven't had any luck.

From a bit of testing it seems that whenever the min value is greater than zero, the handle initially positions itself off the slide track. Am I perhaps doing something incorrect?

**Comment by strange-developer** [comment]
I've done some hacking and figured out that in the linear algorithm, this could change:

```
    function getPosition(value, min, max) {
      const position = (value - min) / (max - min) * 100;
      return position < 0 ? 0 : position;
    }
```

Probably not the most elegant solution but this is where I've locked down the issue to.

**Comment by HeroSizy** [comment]
[algorithms example](https://github.com/airbnb/rheostat/tree/master/src/algorithms)

this may help

**Comment by strange-developer** [comment]
Thanks
