### ISSUE TITLE
Any chance of a new release ?

### ISSUE THREAD

**Issue by matfin** [airbnb/rheostat#147]
Hi,

Thanks for creating this great package, which I am putting to good use. Would it be possible to put out a new release though? 

It would be great to finally get rid of the messages like the ones below (which [PR#138](https://github.com/airbnb/rheostat/pull/138)) addresses.

```
Warning: Expected `onMouseDown` listener to be a function, instead got `false`.
    
    If you used to conditionally omit it with onMouseDown={condition && value}, pass onMouseDown={condition ? value : undefined} instead.
        in button (created by Button)
        in Button (created by Rheostat)
        in div (created by Rheostat)
        in Rheostat (created by Slider)
        in div (created by <snip>)
        in <snip> (created by <snip>)
        in div (created by <snip>)
        in div (created by <snip>)
        in <snip> (created by <snip>)
        in <snip> (created by <snip>)
        in <snip>
```

Many thanks

**Comment by ljharb** [comment]
The next release will be semver-major due to dropping React 0.13 support, so it might not be released very soon.

**Comment by elgubbo** [comment]
@ljharb that is disappointing :(

**Comment by matfin** [comment]
Hi there,

Thanks for the response. If there is anything I can do to assist please let me know :)

**Comment by matfin** [comment]
Offer still stands.

**Comment by ljharb** [comment]
v2.2.0 is released.
