### ISSUE TITLE
'rheostat/initialize' imports non transpiled verison of DefaultTheme

### ISSUE THREAD

**Issue by samouss** [airbnb/rheostat#181]
The latest version now requires the script `rheostat/initialize` to be loaded. But this module requires a non transpiled verison of the `DefaultTheme`. 

```
ERROR in ./node_modules/rheostat/src/themes/DefaultTheme.js
Module parse failed: Unexpected token (24:6)
You may need an appropriate loader to handle this file type.
| 
|     color: {
|       ...core,
|       progressBar: core.teal,
|       focus: core.teal,
 @ ./node_modules/rheostat/scripts/utils/registerInterfaceWithDefaultTheme.js 2:0-57
 @ ./node_modules/rheostat/scripts/utils/registerCSSInterfaceWithDefaultTheme.js
 @ ./node_modules/rheostat/lib/initialize.js
 @ ./node_modules/rheostat/initialize.js
 @ ./stories/3rdPartyIntegrations.stories.js
 @ ./stories \.stories\.js$
 @ ./storybook/config.js
 @ multi ./node_modules/@storybook/react/dist/server/config/polyfills.js ./node_modules/@storybook/react/dist/server/config/globals.js ./node_modules/webpack-hot-middleware/client.js?reload=true ./storybook/config.js
```

The import from `registerInterfaceWithDefaultTheme ` target the source file of `DefaultTheme` under `src` rather than the transpiled version in the `lib` folder. A possible solution is to move the two files that register the `DefaultTheme` under the `src` folder.

https://github.com/airbnb/rheostat/blob/7db67ca614fd13cb4e5a5eb861f33cf7e9c6da29/scripts/utils/registerInterfaceWithDefaultTheme.js#L1-L7

**Comment by majapw** [comment]
I think this is because we're not building the scripts folder. It seems like it would make sense to move the theme registration to the src folder. @philipfweiss can you take a look?

**Comment by philipfweiss** [comment]
@majapw yup!

**Comment by philipfweiss** [comment]
Addressed with https://github.com/airbnb/rheostat/pull/182!
