### ISSUE TITLE
[Question] What is the best way to use Rheostat in other component ?

### ISSUE THREAD

**Issue by minhtranite** [airbnb/rheostat#200]
I want to use Rheostat and react-dates in a shared component (a library) but it require initialize step: `import 'rheostat/initialize';`. 

I have some questions:
1. Where I should put the initialize script ? in the component or in app use the component ?
2. How can I change a little bit styles in component and allow the app override that styles if need ?

**Comment by ljharb** [comment]
In the top-level app. The app can override them for rheostat the same way as a transitive dep as a top-level dep.

**Comment by minhtranite** [comment]
@ljharb Thank for quick response!

It able to generate only css class name without styles ? I'm not fan of `css in js`. I mean i just want css class and then I will write css in my global css file.

**Comment by ljharb** [comment]
You can use the css [here](https://unpkg.com/rheostat@3.0.1/css/rheostat.css).

**Comment by minhtranite** [comment]
Yes i know. But I mean I just want keep initialize step inside the component also keep there css classes bellow are original (not generate with suffix). So it easy to override the styles in app used component and don't care about what technology used inside component.

![screen shot 2018-11-22 at 10 38 27 am](https://user-images.githubusercontent.com/5418628/48880511-69337680-ee43-11e8-834a-bbe483a1a191.png)

**Comment by minhtranite** [comment]
@ljharb yes. Thank for you support.
