### ISSUE TITLE
build failure on windows 10

### ISSUE THREAD

**Issue by marchage** [airbnb/rheostat#222]
Helloooow,

If you change this line in package.json:
```
"prebuild:css": "rimraf lib/css && mkdir -p lib/css",
```
to the following:
```
"prebuild:css": "rimraf lib/css && mkdirp lib/css",
```
...and make [mkdirp](https://www.npmjs.com/package/mkdirp) a dev-dependency (`npm install --save-dev mkdirp`), the build command will run on Windows 10 with npm command run from powershell. Haven't tested that package (mkdirp) on linux or mac.

Hope this helps, Marc

**Comment by ljharb** [comment]
Sure, seems like a reasonable fix.
