### ISSUE TITLE
Bundle size increased to almost 100Kb minified

### ISSUE THREAD

**Issue by felixmosh** [airbnb/rheostat#268]
Thank you for sharing & maintaining this awesome lib.

I've noticed that since 2 major versions bundle size of the lib was jumped to more than 6X.

![image](https://user-images.githubusercontent.com/9304194/67669531-c486b680-f97a-11e9-96c4-9abb0522070c.png)

**Comment by StarpTech** [comment]
What's the name of the tool? They probably publish the full package to NPM this doesn't mean you will include it in your app. We experience no extraordinary size in the final build.

**Comment by felixmosh** [comment]
https://bundlephobia.com/result?p=rheostat@4.1.0

**Comment by ljharb** [comment]
Installed size is irrelevant; bundle size is far too nuanced for each app for bundlephobia’s numbers to be useful, and doesn’t account for deduping.

Thanks for sharing what you’ve noticed.
