### ISSUE TITLE
@types/rheostat values

### ISSUE THREAD

**Issue by george-dotdev** [airbnb/rheostat#277]
I have created a PR on @types/rheostat to change the types of the `value` state and props. Currently the types will accept any length of numbered array. `number[]`. As I understand this will only ever contain 2 values - min and max. Therefore I propose to change this to `[number, number]`.

I have opened this issue to get some feedback on this PR and create some additional context around the issue.

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43191

**Comment by ljharb** [comment]
Thanks, I'll take a look; closing this here, though, since this package doesn't maintain types.
