### ISSUE TITLE
Background Chart Example

### ISSUE THREAD

**Issue by danny-waite** [airbnb/rheostat#283]
Is there an example of adding a background chart as in the example as shown in the header of the README? Looking at the storybooks, I can't see one.  Would love some pointers on how to recreate that.  Did I miss something? TIA

**Comment by sayurimizuguchi** [comment]
Hey @danny-waite, you can see a code sandbox example here https://codesandbox.io/s/airbnb-rheostat-4hloh

**Comment by danny-waite** [comment]
Thanks Sayuri, much appreciated.
