### ISSUE TITLE
Warning when click/tap slider icon es6

### ISSUE THREAD

**Issue by kingr** [airbnb/rheostat#30]
`warning.js:45 Warning: ReactDOMComponent: Do not access .getDOMNode() of a DOM node; instead, use the node directly. This DOM node was rendered by `Slider`.`

I'm getting this warning in React 0.14.6 when clicking/tap the slider icon. I'm using es6 class components with Babel.

**Comment by goatslacker** [comment]
It's a warning that goes away when you're using React 15. Removing this warning in React14 would require me doing some version sniffing which I'm not crazy about.
