### ISSUE TITLE
This synthetic event is reused for performance reasons.

### ISSUE THREAD

**Issue by EngineeredTruth** [airbnb/rheostat#32]
Getting this error in chrome console when using custom slider with 1 handle on each side.

commons.js:1342 Warning: This synthetic event is reused for performance reasons. If you're seeing this, you're adding a new property in the synthetic event object. The property is never released. See https://fb.me/react-event-pooling for more information.

Error alerts in this section of react:

```
    if (process.env.NODE_ENV !== 'production') {
      (function () {
        var printWarning = function printWarning(format) {
          for (var _len = arguments.length, args = Array(_len > 1 ? _len - 1 : 0), _key = 1; _key < _len; _key++) {
            args[_key - 1] = arguments[_key];
          }

          var argIndex = 0;
          var message = 'Warning: ' + format.replace(/%s/g, function () {
            return args[argIndex++];
          });
          if (typeof console !== 'undefined') {
            console.error(message); \\ERROR IS CONSOLE LOGGED HERE
          }
          try {
            // --- Welcome to debugging React ---
            // This error was thrown as a convenience so that you can use this stack
            // to find the callsite that caused this warning to fire.
            throw new Error(message);
          } catch (x) {}
        };

```

**Comment by goatslacker** [comment]
Probably has to do with these lines: https://github.com/airbnb/rheostat/blob/master/src/Slider.jsx#L578-L579

They're not really necessary. Want to remove them in a PR?

**Comment by EngineeredTruth** [comment]
I removed the code and it removed the error. Thank you!

**Comment by TedAvery** [comment]
I'm still getting this error, regardless of the number of handles I am using.

**Comment by goatslacker** [comment]
It has nothing to do with the handles but rather with the code [here](https://github.com/airbnb/rheostat/blob/master/src/Slider.jsx#L578-L579).

**Comment by Leimi** [comment]
For information, I tried removing the lines and there were problems with the handle not moving anymore (react 15). Didn't go much further.

**Comment by goatslacker** [comment]
This was already removed here: https://github.com/airbnb/rheostat/commit/be7e38009268823b4af53324c968a0b362c99fab#diff-4dfae13f53a5af8d1382d6a704e2ec40L567

**Comment by Leimi** [comment]
oops, my bad!

**Comment by goatslacker** [comment]
It's all good. I realized my old link pointed to `master` so I've edited that as well.
