### ISSUE TITLE
Thoughts on adding a `handleProps` on the Slider component?

### ISSUE THREAD

**Issue by Leimi** [airbnb/rheostat#43]
Hi,

Using the slider, I found a bit cumbersome to add custom props on the slider handles. What do you think about having a `handleProps` on the `<Slider>` that would be destructured into the `<Handle>`? It would simplify small customizations that don't necessarily require a whole new component.

My use case is I want to add a `aria-labelledby` attribute to the Handle.

Currently, to do this I need to create a new Handle component specific to the Slider I create. For example:

```es6
const MyHandle = ({...props}) =>
  <button
    {...props}
    type="button"
    aria-labelledby="aLabelId"
  />;

[...]

<Rheostat handle={MyHandle} />
```

With a `handleProps` I could do:

```es6
<Rheostat handleProps={{
  aria-labelledby="aLabelId"
}} />
```

**Comment by ljharb** [comment]
Using aria props is always a fallback when not using native HTML semantics - the proper way to label a button is to both nest and use for-ID linking - namely, wrap Rheostat in a label, and provide an ID for the handle as a prop - *that* is what I'd support adding.

**Comment by Leimi** [comment]
> Using aria props is always a fallback when not using native HTML semantics

Isn't it what were are doing here, building a slider component with divs and buttons?

> the proper way to label a button is to both nest and use for-ID linking

I can't quite follow you - isn't the usual way to label a button just to have some text in it?
To see if I understand correctly, what you say we should do looks like this in the HTML:

```html
<label for="handleId">
	<div class="rheostat">
		<div class="rheostat-background"></div>
		<button class="rheostat-handle" [...] id="handleId"></button>
		<div class="rheostat-progress"></div>
	</div>
</label>
```

Seems weird to me to have both the ID and the nesting, maybe I don't get it?
___________
Anyway, in the [wai-aria authoring practices described here](https://www.w3.org/TR/wai-aria-practices-1.1/#slider), they mention the usage of *aria-labelledby* as the way to label the slider. If we want to implement the WAI-ARIA slider design pattern, why wouldn't that be OK to use this attribute?

I feel all of this is not _that_ related to the original `handleProps` suggestion though ;)

**Comment by Leimi** [comment]
Thinking about it, this `handleProps` thing works great if using only one handle but could probably be weird if using multiple handles.

**Comment by goatslacker** [comment]
What's so bad about creating a new component for the handles?

**Comment by Leimi** [comment]
It's not that bad :) But I found it a bit overkill when only needing to add a few props to the default handle.

**Comment by felixgirault** [comment]
Hi everyone,

In the multi-thumb slider examples shown in the [spec](https://www.w3.org/TR/wai-aria-practices/#slidertwothumb), each handle can have its own label ([here](http://files.paciellogroup.com/blogmisc/samples/aria/slider/doubleslider.html) and [here](http://www.oaa-accessibility.org/examplep/slider1/)).
Given any of the proposed methods, how should one label multiple handles correctly ?

I don't see that working by providing a custom handle component, because we can only provide one for the slider, and not one for each handle.
Also, wrapping the slider within two labels seems a little weird to me, but I may have missed something.

What do you guys think ?

**Comment by goatslacker** [comment]
@felixgirault you already get a `data-handle-key` prop for each handle which contains a 0-based index of what position the handle is in. You can use that to determine how you want to render each handle.

**Comment by goatslacker** [comment]
@Leimi it's certainly convenient to have a `handleProps` prop but I feel it is adding too much API to support all cases.

**Comment by Leimi** [comment]
Sure, I see what you mean!
