### ISSUE TITLE
Can a new version be released?

### ISSUE THREAD

**Issue by Haroenv** [airbnb/rheostat#79]
In #73 the move from React.PropTypes to PropTypes has happened, but this hasn't been released yet, could that be done? Thanks!

**Comment by nielsvanmidden** [comment]
What are we waiting for?

**Comment by devCrossNet** [comment]
@goatslacker is this package still maintained or should I go for an alternative. just asking if I can rely on it for a new project.

Great work btw! :-)

**Comment by ljharb** [comment]
The package is still maintained.

We'll try to release soon.

**Comment by ljharb** [comment]
v2.1.1 is released.

**Comment by devCrossNet** [comment]
@ljharb thank you very much!

**Comment by Haroenv** [comment]
Awesome!
