### ISSUE TITLE
TypeError in IE 10 

### ISSUE THREAD

**Issue by homs44** [airbnb/rheostat#96]
When i use this component in IE 10, Error is occurred on console like below.
TypeError :  Unable to get property 'max' of undefined or null reference
  at Rheostat ( xxxxxx bundle.js :5 : 667 )
  at g._constructComponentWithoutOwnner..
  .
  .
  .

also  bundle.js:5:667 is 
Object.getPrototypeOf(Rheostat).call(this,e)),n=t.props,r=**n.max**,i=n.min,o=n.values;
I check the code 5:667 to bold text

**Comment by ljharb** [comment]
How are you shimming `Object.getPrototypeOf`? You should be using https://npmjs.com/airbnb-browser-shims or the equivalent.

**Comment by homs44** [comment]
Thank you. I solved this problem. !!
