### ISSUE TITLE
Slider.jsx Unexpected token 

### ISSUE THREAD

**Issue by jchapelle** [airbnb/rheostat#98]
I've just installed rheostat with yarn and added the import line in my code. I'm getting the following errors.
I don't understand what I must do ...

```
Uncaught (in promise) Error: Module parse failed: /home/jchapelle/project/frontend-realestate/node_modules/rheostat/src/Slider.jsx Unexpected token (34:11)
You may need an appropriate loader to handle this file type.
| class Button extends React.Component {
|   render() {
|     return <button {...this.props} type="button" />;
|   }
| }
```

**Comment by ljharb** [comment]
Import from lib, not src.

**Comment by jchapelle** [comment]
Thanks you so much

**Comment by seanlindo** [comment]
@ljharb @jchapelle 

Can you paste a snippet on how you imported from lib and not src?

`import rheostat from 'rheostat'` is loading from the src folder for some reason.

**Comment by seanlindo** [comment]
`import Rheostat from 'rheostat/lib/Slider'` was the command I had to run for my particular webpack + babel solution.

**Comment by ljharb** [comment]
@seanlindo that shouldn't be required; `import Rheostat from 'rheostat'` should be sufficient. If that's not the case, your webpack setup might need fixing.
